#!/usr/bin/env bash
if [ -z "$PYFILE" ]; then
    echo "Error: PYFILE environment variable is not set."
    exit 1
fi
python3 -m py_compile "$PYFILE" && echo "Compiling $PYFILE ..." || echo "Compilation of $PYFILE failed."
