#!/bin/bash
echo "Compiling $PYFILE ..."
python3 -m py_compile "$PYFILE"
mv __pycache__/"$(basename "$PYFILE" .py).cpython-$(python3 -c 'import sys; print(sys.version_info.major * 10 + sys.version_info.minor)').pyc" "${PYFILE}c"
rmdir __pycache__ 2>/dev/null
